[build]
command = "composer install"
dockerfile = "Dockerfile"

[env]
DB_CONNECTION="mysql"
DB_HOST="mysql"
DB_PORT="3306"
DB_DATABASE="laravel_db"
DB_USERNAME="laravel_user"
DB_PASSWORD="laravel_pass"